### ISSUE TITLE
How to use this in Code Igniter 4

### ISSUE THREAD

**Issue by joshw378** [PhiloNL/CodeIgniter-Route-Debugging#2]
question as the title , tks !

**Comment by PhiloNL** [comment]
No idea, sorry about that, this repo is over 9 years and hasn't used CodeIgniter for a very long time. Maybe someone within the CodeIgniter community can assist you https://codeigniter.com/discuss

**Comment by joshw378** [comment]
All right , I see the problem , Thanks Your time Anyway !
